require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cohorts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Cohort. As you add validations to Cohort, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cohort.create! valid_attributes
      get cohorts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cohort = Cohort.create! valid_attributes
      get cohort_url(cohort)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cohort_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cohort = Cohort.create! valid_attributes
      get edit_cohort_url(cohort)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cohort" do
        expect {
          post cohorts_url, params: { cohort: valid_attributes }
        }.to change(Cohort, :count).by(1)
      end

      it "redirects to the created cohort" do
        post cohorts_url, params: { cohort: valid_attributes }
        expect(response).to redirect_to(cohort_url(Cohort.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cohort" do
        expect {
          post cohorts_url, params: { cohort: invalid_attributes }
        }.to change(Cohort, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cohorts_url, params: { cohort: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cohort" do
        cohort = Cohort.create! valid_attributes
        patch cohort_url(cohort), params: { cohort: new_attributes }
        cohort.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cohort" do
        cohort = Cohort.create! valid_attributes
        patch cohort_url(cohort), params: { cohort: new_attributes }
        cohort.reload
        expect(response).to redirect_to(cohort_url(cohort))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cohort = Cohort.create! valid_attributes
        patch cohort_url(cohort), params: { cohort: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cohort" do
      cohort = Cohort.create! valid_attributes
      expect {
        delete cohort_url(cohort)
      }.to change(Cohort, :count).by(-1)
    end

    it "redirects to the cohorts list" do
      cohort = Cohort.create! valid_attributes
      delete cohort_url(cohort)
      expect(response).to redirect_to(cohorts_url)
    end
  end
end
