require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cohorts", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Cohort. As you add validations to Cohort, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      cohort_name: "Charlie",
      cohort_year: "2022"
    }
  }

  let(:invalid_attributes) {
    {
      cohort_name: nil,
      cohort_year: nil
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CohortsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cohort.create! valid_attributes
      get cohorts_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cohort = Cohort.create! valid_attributes
      get cohort_url(cohort), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cohort" do
        expect {
          post cohorts_url,
            params: {cohort: valid_attributes}, headers: valid_headers, as: :json
        }.to change(Cohort, :count).by(1)
      end

      it "renders a JSON response with the new cohort" do
        post cohorts_url,
          params: {cohort: valid_attributes}, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cohort" do
        expect {
          post cohorts_url,
            params: {cohort: invalid_attributes}, as: :json
        }.to change(Cohort, :count).by(0)
      end

      it "renders a JSON response with errors for the new cohort" do
        post cohorts_url,
          params: {cohort: invalid_attributes}, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          cohort_name: "Delta",
          cohort_year: "2023"
        }
      }

      it "updates the requested cohort" do
        cohort = Cohort.create! valid_attributes
        patch cohort_url(cohort),
          params: {cohort: new_attributes}, headers: valid_headers, as: :json
        cohort.reload
        expect(response).to be_successful
      end

      it "renders a JSON response with the cohort" do
        cohort = Cohort.create! valid_attributes
        patch cohort_url(cohort),
          params: {cohort: new_attributes}, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the cohort" do
        cohort = Cohort.create! valid_attributes
        patch cohort_url(cohort),
          params: {cohort: invalid_attributes}, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cohort" do
      cohort = Cohort.create! valid_attributes
      expect {
        delete cohort_url(cohort), headers: valid_headers, as: :json
      }.to change(Cohort, :count).by(-1)
    end
  end
end
